/* istanbul ignore file -- justification: this is simply a configuration file; no testing needed */

import { library } from '@fortawesome/fontawesome-svg-core';

import {
  faCompass as farFaCompass,
  faFrown as farFaFrown,
  faSquare as farFaSquare,
  faSquareCheck as farFaSquareCheck,
  faTimesCircle as farFaTimesCircle
} from '@fortawesome/pro-regular-svg-icons';

import {
  faAddressCard as fasFaAddressCard,
  faAngleDoubleLeft as fasFaAngleDoubleLeft,
  faAngleDoubleRight as fasFaAngleDoubleRight,
  faAngleLeft as fasFaAngleLeft,
  faAngleRight as fasFaAngleRight,
  faBell as fasFaBell,
  faBookSection as fasFaBookSection,
  faBriefcase as fasFaBriefcase,
  faBuildingShield as fasFaBuildingShield,
  faCalendarDays as fasFaCalendarDays,
  faCaretDown as fasFaCaretDown,
  faCaretUp as fasFaCaretUp,
  faChartLineUp as fasFaChartLineUp,
  faCheck as fasFaCheck,
  faCheckCircle as fasFaCheckCircle,
  faCircleExclamation as fasFaCircleExclamation,
  faCircle as fasFaCircle,
  faCircleCheck as fasFaCircleCheck,
  faCircleDot as fasFaCircleDot,
  faCircleInfo as fasFaCircleInfo,
  faCircleLocationArrow as fasFaCircleLocationArrow,
  faCirclePlus as fasFaCirclePlus,
  faCircleX as fasFaCircleX,
  faCircleXmark as fasFaCircleXmark,
  faCog as fasFaCog,
  faCommentArrowUpRight as fasFaCommentArrowUpRight,
  faDollarSign as fasFaDollarSign,
  faEllipsisH as fasFaEllipsisH,
  faFileInvoiceDollar as fasFaFileInvoiceDollar,
  faFileUser as fasFaFileUser,
  faFolderUser as fasFaFolderUser,
  faHandHoldingSeedling as fasFaHandHoldingSeedling,
  faHandshake as fasFaHandshake,
  faIdCard as fasFaIdCard,
  faInfoCircle as fasFaInfoCircle,
  faMessageLines as fasFaMessageLines,
  faPaperclip as fasFaPaperclip,
  faPenToSquare as fasFaPenToSquare,
  faPeopleGroup as fasFaPeopleGroup,
  faPercent as fasFaPercent,
  faPersonCircleCheck as fasFaPersonCircleCheck,
  faQuestionCircle as fasFaQuestionCircle,
  faShieldExclamation as fasFaShieldExclamation,
  faShieldMinus as fasFaShieldMinus,
  faShieldPlus as fasFaShieldPlus,
  faThoughtBubble as fasFaThoughtBubble,
  faTimelineArrow as fasFaTimelineArrow,
  faTriangleExclamation as fasFaTriangleExclamation,
  faUpToLine as fasFaUpToLine,
  faUserGroup as fasFaUserGroup,
  faX as fasFaX,
  faXmark as fasFaXmark
} from '@fortawesome/pro-solid-svg-icons';

library.add(farFaCompass, farFaFrown, farFaSquare, farFaSquareCheck, farFaTimesCircle);

library.add(
  fasFaAddressCard,
  fasFaAngleDoubleLeft,
  fasFaAngleDoubleRight,
  fasFaAngleLeft,
  fasFaAngleRight,
  fasFaBell,
  fasFaBookSection,
  fasFaBriefcase,
  fasFaBuildingShield,
  fasFaCalendarDays,
  fasFaCaretDown,
  fasFaCaretUp,
  fasFaChartLineUp,
  fasFaCircleExclamation,
  fasFaCheck,
  fasFaCheckCircle,
  fasFaCircle,
  fasFaCircleCheck,
  fasFaCircleDot,
  fasFaCircleInfo,
  fasFaCircleLocationArrow,
  fasFaCirclePlus,
  fasFaCircleX,
  fasFaCircleXmark,
  fasFaCog,
  fasFaCommentArrowUpRight,
  fasFaDollarSign,
  fasFaEllipsisH,
  fasFaFileInvoiceDollar,
  fasFaFileUser,
  fasFaFolderUser,
  fasFaHandHoldingSeedling,
  fasFaHandshake,
  fasFaIdCard,
  fasFaInfoCircle,
  fasFaMessageLines,
  fasFaPaperclip,
  fasFaPenToSquare,
  fasFaPeopleGroup,
  fasFaPercent,
  fasFaPersonCircleCheck,
  fasFaQuestionCircle,
  fasFaShieldExclamation,
  fasFaShieldMinus,
  fasFaShieldPlus,
  fasFaThoughtBubble,
  fasFaTimelineArrow,
  fasFaTriangleExclamation,
  fasFaUpToLine,
  fasFaUserGroup,
  fasFaX,
  fasFaXmark
);
